spring.application.name=backend
server.port=8080

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/certificate_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Huyle2005@
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Blockchain
blockchain.node.url=http://127.0.0.1:8545
blockchain.contract.address=0x5FbDB2315678afecb367f032d93F642f64180aa3
blockchain.admin.key=0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
# key là c?a account 0

# key ?? m?, khóa private key c?a nhà tr??ng trv khi l?u và db
# dùng thu?t toán AES-256
wallet.encryption.key=MySecretKeyForWalletEncryption19

# JWT - Tách riêng th?i gian h?t h?n c?a 2 lo?i token
jwt.secret=HuyLe_my-super-secret-key-for-jwt-token-256-bit-long
jwt.access.expiration=900000       
jwt.refresh.expiration=604800000  